import { PrismaClient, ProductBadge } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Clear existing data
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.address.deleteMany();
  await prisma.customer.deleteMany();
  await prisma.product.deleteMany();
  await prisma.chickenBreed.deleteMany();
  await prisma.newsletterSubscriber.deleteMany();
  await prisma.contactMessage.deleteMany();

  // Seed Products
  const products = [
    // ==================== PORC ====================
    {
      name: 'Porc Entier Mort',
      slug: 'porc-entier-mort',
      category: 'porc',
      description: 'Porc entier déjà abattu, élevé dans nos enclos spacieux à la Ferme du Vardier. Vendu au kg, idéal pour les grandes occasions, mariages et événements familiaux.',
      shortDescription: 'Porc entier mort de notre élevage, vendu au kg.',
      price: 12000,
      images: ['/images/porc/test4.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['populaire'] as ProductBadge[],
      characteristics: ['Vendu au kg', 'Élevage responsable', 'Sans antibiotiques de croissance', 'Livraison possible'],
      weight: '1 kg',
    },
    {
      name: 'Demi Porc',
      slug: 'demi-porc',
      category: 'porc',
      description: 'Demi-porc de notre élevage, parfait pour les familles ou les petits restaurants.',
      shortDescription: 'Demi-porc frais, idéal pour les familles.',
      price: 420000,
      images: ['/images/porc/WhatsApp Image 2026-02-17 at 00.43.17.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['populaire'] as ProductBadge[],
      characteristics: ['Poids: 40-50 kg', 'Coupe au choix', 'Viande fraîche'],
      weight: '40-50 kg',
    },
    // ==================== POISSON (Tilapia de Madagascar) ====================
    {
      name: 'Tilapia - Lot de 5kg',
      slug: 'tilapia-lot-5kg',
      category: 'poisson',
      description: 'Lot économique de 5kg de tilapia frais de Madagascar. Idéal pour les familles et les restaurants.',
      shortDescription: 'Lot économique de tilapia malgache.',
      price: 90000,
      originalPrice: 100000,
      images: ['/images/poisson/poisson1.jpg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['promo', 'populaire'] as ProductBadge[],
      characteristics: ['Poids: 5 kg', 'Économie de 10 000 Ar', 'Fraîcheur garantie', 'Tilapia de Madagascar'],
      weight: '5 kg',
    },
    {
      name: 'Tilapia Entier (pièce)',
      slug: 'tilapia-entier-piece',
      category: 'poisson',
      description: 'Tilapia entier de Madagascar, prêt à cuisiner. Parfait pour griller ou braiser à la malgache.',
      shortDescription: 'Tilapia entier frais, prêt à cuisiner.',
      price: 12000,
      images: ['/images/poisson/poisson1.jpg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau'] as ProductBadge[],
      characteristics: ['Poids: 500-700g par pièce', 'Poisson entier', 'Parfait pour grillades', 'Produit local'],
      weight: '500-700g',
    },
    // ==================== POULET / VOLAILLE ====================
    {
      name: 'Akoho Gasy (Poulet Entier)',
      slug: 'akoho-gasy-poulet-entier',
      category: 'poulet',
      description: 'Poulet fermier malgache (Akoho Gasy) élevé en plein air à la Ferme du Vardier. Chair ferme et savoureuse, idéal pour les plats traditionnels.',
      shortDescription: 'Poulet fermier malgache entier, élevé en plein air.',
      price: 25000,
      images: ['/images/chickens/Akoho1.jpeg', '/images/chickens/Akoho2.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Poids: 1,5-2 kg', 'Élevé en plein air', 'Alimentation naturelle', 'Chair ferme et savoureuse'],
      weight: '1,5-2 kg',
    },
    {
      name: 'Poule Soie Mâle',
      slug: 'poule-soie-male',
      category: 'poulet',
      description: 'Coq Soie élevé à la Ferme du Vardier. Race ornementale au plumage soyeux unique, très apprécié pour son caractère docile et son apparence exceptionnelle.',
      shortDescription: 'Coq Soie, race ornementale au plumage soyeux.',
      price: 40000,
      images: ['/images/chickens/Akoho3.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'nouveau'] as ProductBadge[],
      characteristics: ['Race ornementale', 'Plumage soyeux', 'Caractère docile', 'Élevé en plein air'],
      weight: '1-1,5 kg',
    },
    {
      name: 'Brahma Femelle',
      slug: 'brahma-femelle',
      category: 'poulet',
      description: 'Poule Brahma femelle, une race majestueuse et robuste élevée à la Ferme du Vardier. Excellente pondeuse et volaille d\'ornement très appréciée.',
      shortDescription: 'Poule Brahma femelle, race noble et majestueuse.',
      price: 35000,
      images: ['/images/chickens/Akoho4.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'nouveau'] as ProductBadge[],
      characteristics: ['Race noble', 'Excellente pondeuse', 'Élevée en plein air', 'Plumage magnifique'],
      weight: '3-4 kg',
    },
    {
      name: 'Caille Entière',
      slug: 'caille-entiere',
      category: 'caille',
      description: 'Caille fermière élevée à la Ferme du Vardier. Viande délicate et raffinée, parfaite pour les repas gastronomiques.',
      shortDescription: 'Caille fermière entière, viande délicate.',
      price: 15000,
      images: ['/images/caille/caille1.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau', 'plein_air'] as ProductBadge[],
      characteristics: ['Poids: 150-200g', 'Viande délicate', 'Élevage fermier', 'Idéal pour repas gastronomique'],
      weight: '150-200g',
    },
    {
      name: 'Akanga (Pintade)',
      slug: 'akanga-pintade',
      category: 'akanga',
      description: 'Pintade (Akanga) élevée en plein air à la Ferme du Vardier. Viande goûteuse et savoureuse, entre le poulet et le gibier.',
      shortDescription: 'Pintade fermière entière, viande savoureuse.',
      price: 35000,
      images: ['/images/akanga/akanga.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Poids: 1-1,5 kg', 'Viande goûteuse', 'Élevé en plein air', 'Entre poulet et gibier'],
      weight: '1-1,5 kg',
    },
    // Anciens produits désactivés
    {
      name: 'Poulet Entier Fermier',
      slug: 'poulet-entier-fermier',
      category: 'poulet',
      description: 'Poulet fermier élevé en plein air à la Ferme du Vardier. Chair ferme et savoureuse, idéal pour les rôtis du dimanche.',
      shortDescription: 'Poulet fermier entier élevé en plein air.',
      price: 35000,
      images: ['https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Poids: 1,5-2 kg', 'Élevé en plein air', 'Alimentation naturelle', 'Chair ferme et savoureuse'],
      weight: '1,5-2 kg',
    },
    {
      name: 'Cuisses de Poulet (1kg)',
      slug: 'cuisses-de-poulet-1kg',
      category: 'poulet',
      description: 'Cuisses de poulet fermier, parfaites pour grillades ou braisées.',
      shortDescription: 'Cuisses de poulet fermier tendres et juteuses.',
      price: 22000,
      images: ['https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air'] as ProductBadge[],
      characteristics: ['Poids: 1 kg', 'Viande tendre', 'Parfait pour grillades'],
      weight: '1 kg',
    },
    {
      name: 'Filets de Poulet (1kg)',
      slug: 'filets-de-poulet-1kg',
      category: 'poulet',
      description: 'Filets de poulet fermier, viande maigre et tendre pour tous vos plats.',
      shortDescription: 'Filets de poulet maigres et tendres.',
      price: 28000,
      images: ['https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Poids: 1 kg', 'Viande maigre', 'Sans peau', 'Idéal pour régime'],
      weight: '1 kg',
    },
    {
      name: 'Ailes de Poulet (1kg)',
      slug: 'ailes-de-poulet-1kg',
      category: 'poulet',
      description: 'Ailes de poulet fermier, parfaites pour les apéritifs et les grillades.',
      shortDescription: 'Ailes de poulet croustillantes pour apéritifs.',
      price: 18000,
      images: ['https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['populaire'] as ProductBadge[],
      characteristics: ['Poids: 1 kg', 'Idéal pour apéritifs', 'Facile à préparer'],
      weight: '1 kg',
    },
    {
      name: 'Lot de 5 Poulets Fermiers',
      slug: 'lot-5-poulets-fermiers',
      category: 'poulet',
      description: 'Lot économique de 5 poulets fermiers entiers. Parfait pour les grandes familles ou les événements.',
      shortDescription: 'Lot économique de 5 poulets fermiers.',
      price: 160000,
      originalPrice: 175000,
      images: ['https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['promo', 'plein_air'] as ProductBadge[],
      characteristics: ['5 poulets entiers', 'Économie de 15 000 Ar', 'Livraison possible'],
      quantity: 5,
    },
    // ==================== TRANSFORMÉS (Désactivé) ====================
    {
      name: 'Lard Fumé (500g)',
      slug: 'lard-fume-500g',
      category: 'transformes',
      description: 'Lard fumé artisanalement sur bois de fruit.',
      shortDescription: 'Lard fumé artisanal pour cuisine.',
      price: 18000,
      images: ['/images/porc/test4.jpeg'],
      inStock: false,
      stockQuantity: 0,
      badges: [] as ProductBadge[],
      characteristics: ['Poids: 500 g', 'Fumage au bois de fruit', 'Goût authentique'],
      weight: '500 g',
    },
    // ==================== ŒUFS FRAIS ====================
    {
      name: 'Œufs d\'Été - Boîte de 6',
      slug: 'oeufs-ete-boite-6',
      category: 'oeufs_frais',
      description: 'Nos œufs d\'été proviennent de poules élevées en plein air à la Ferme du Vardier. Fraîcheur garantie et qualité exceptionnelle.',
      shortDescription: 'Œufs frais de saison, boîte de 6.',
      price: 15000,
      images: ['/images/products/Oeuf1.jpeg'],
      inStock: true,
      stockQuantity: 50,
      badges: ['nouveau', 'plein_air'] as ProductBadge[],
      characteristics: ['Poules élevées en plein air', 'Ramassage quotidien', 'Fraîcheur garantie', 'Produit de saison'],
      quantity: 6,
    },
    {
      name: 'Œufs Bio - Boîte de 6',
      slug: 'oeufs-bio-boite-6',
      category: 'oeufs_frais',
      description: 'Nos œufs bio proviennent de poules élevées en plein air, nourries exclusivement avec des aliments certifiés agriculture biologique.',
      shortDescription: 'Œufs frais de poules élevées en plein air, certifiés bio.',
      price: 20000,
      images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['bio', 'plein_air'] as ProductBadge[],
      characteristics: ['Certification Agriculture Biologique AB', 'Poules élevées en plein air', 'Ramassage quotidien', 'Calibre moyen à gros'],
      quantity: 6,
    },
    {
      name: 'Œufs Bio - Boîte de 12',
      slug: 'oeufs-bio-boite-12',
      category: 'oeufs_frais',
      description: 'Notre boîte familiale de 12 œufs bio, idéale pour les familles ou les amateurs de pâtisserie.',
      shortDescription: 'Format familial de nos délicieux œufs bio.',
      price: 38000,
      originalPrice: 40000,
      images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['bio', 'plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Certification Agriculture Biologique AB', 'Poules élevées en plein air', 'Économie par rapport à la boîte de 6'],
      quantity: 12,
    },
    {
      name: 'Plateau 30 œufs Plein Air',
      slug: 'plateau-30-oeufs-plein-air',
      category: 'oeufs_frais',
      description: 'Le plateau idéal pour les grandes familles ou les professionnels.',
      shortDescription: 'Grand plateau de 30 œufs pour les familles nombreuses.',
      price: 81000,
      images: ['https://images.unsplash.com/photo-1498654077810-12c21d4d6dc3?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air'] as ProductBadge[],
      characteristics: ['Poules élevées en plein air', 'Format économique', 'Calibre moyen'],
      quantity: 30,
    },
    {
      name: 'Œufs Extra-Frais du Jour - Boîte de 6',
      slug: 'oeufs-extra-frais-jour-6',
      category: 'oeufs_frais',
      description: 'Œufs ramassés le matin même, livrés dans la journée. Fraîcheur maximale garantie.',
      shortDescription: 'Œufs ramassés le matin même pour une fraîcheur optimale.',
      price: 18000,
      images: ['https://images.unsplash.com/photo-1569288052389-dac9b01c9c05?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau', 'plein_air'] as ProductBadge[],
      characteristics: ['Ramassage le jour même', 'Fraîcheur garantie', 'Poules élevées en plein air'],
      quantity: 6,
    },
    {
      name: 'Œufs Gros Calibre - Boîte de 12',
      slug: 'oeufs-gros-calibre-12',
      category: 'oeufs_frais',
      description: 'Sélection de nos plus gros œufs, calibre XL. Parfaits pour la pâtisserie et les omelettes généreuses.',
      shortDescription: 'Œufs calibre XL pour pâtisserie et cuisine.',
      price: 42000,
      images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['populaire'] as ProductBadge[],
      characteristics: ['Calibre XL (+73g)', 'Idéal pour pâtisserie', 'Jaunes généreux'],
      quantity: 12,
    },
    {
      name: 'Œufs de Marans - Boîte de 6',
      slug: 'oeufs-marans-6',
      category: 'oeufs_frais',
      description: 'Œufs de nos poules Marans, célèbres pour leur coquille chocolat. Un délice visuel et gustatif.',
      shortDescription: 'Œufs chocolat de nos Marans, rares et savoureux.',
      price: 25000,
      images: ['https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau', 'plein_air'] as ProductBadge[],
      characteristics: ['Coquille couleur chocolat', 'Race Marans', 'Goût exceptionnel'],
      quantity: 6,
    },
    {
      name: 'Œufs Bleus Araucana - Boîte de 6',
      slug: 'oeufs-bleus-araucana-6',
      category: 'oeufs_frais',
      description: 'Œufs naturellement bleu-vert de nos Araucanas. Une curiosité de la nature à déguster.',
      shortDescription: 'Œufs bleus naturels, une expérience unique.',
      price: 28000,
      images: ['https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau', 'plein_air'] as ProductBadge[],
      characteristics: ['Coquille naturellement bleue', 'Race Araucana', 'Sans colorant'],
      quantity: 6,
    },
    // Œufs fécondés
    {
      name: 'Œufs Fécondés - Boîte de 6',
      slug: 'oeufs-fecondes-boite-6',
      category: 'oeufs_fecondes',
      description: 'Œufs fécondés de notre élevage, prêts pour l\'incubation. Idéal pour démarrer votre propre élevage de poules.',
      shortDescription: 'Œufs fécondés pour incubation, boîte de 6.',
      price: 18000,
      images: ['https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600'],
      inStock: true,
      stockQuantity: 30,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Boîte de 6 œufs', 'Taux de fécondité > 90%', 'Guide d\'incubation inclus', 'Races variées'],
      quantity: 6,
    },
    {
      name: 'Œufs fécondés Marans',
      slug: 'oeufs-fecondes-marans',
      category: 'oeufs_fecondes',
      description: 'Œufs fécondés de notre lignée de Marans noire cuivrée, célèbre pour ses œufs extra-roux.',
      shortDescription: 'Œufs fécondés pour faire naître vos propres Marans.',
      price: 15500,
      images: ['https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air'] as ProductBadge[],
      characteristics: ['Race Marans noire cuivrée', 'Taux de fécondité > 90%', 'Guide d\'incubation inclus'],
      race: 'Marans',
      eggColor: 'Roux foncé',
    },
    {
      name: 'Œufs fécondés Sussex',
      slug: 'oeufs-fecondes-sussex',
      category: 'oeufs_fecondes',
      description: 'Œufs fécondés de Sussex herminée, une race anglaise réputée pour sa docilité.',
      shortDescription: 'Œufs fécondés Sussex, idéal pour débutants.',
      price: 13500,
      images: ['https://images.unsplash.com/photo-1489644484856-f3ddc0adc923?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Race Sussex herminée', 'Caractère docile', 'Parfaite pour débuter'],
      race: 'Sussex',
      eggColor: 'Crème',
    },
    {
      name: 'Œufs fécondés Araucana',
      slug: 'oeufs-fecondes-araucana',
      category: 'oeufs_fecondes',
      description: 'Découvrez les fameux œufs bleus ! L\'Araucana est une race chilienne unique.',
      shortDescription: 'Les fameux œufs bleus pour votre basse-cour.',
      price: 18000,
      images: [],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau'] as ProductBadge[],
      characteristics: ['Œufs naturellement bleus', 'Race originaire du Chili', 'Très rustique'],
      race: 'Araucana',
      eggColor: 'Bleu-vert',
    },
    // Poules vivantes
    {
      name: 'Poule Rousse Pondeuse',
      slug: 'poule-rousse-pondeuse',
      category: 'poules',
      description: 'Notre poule rousse fermière est une valeur sûre ! Pondeuse exceptionnelle.',
      shortDescription: 'La poule pondeuse par excellence, productive et docile.',
      price: 81000,
      images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['250-300 œufs par an', 'Ponte dès 20-22 semaines', 'Caractère docile'],
      race: 'Rousse fermière',
      eggColor: 'Brun',
    },
    {
      name: 'Poule Sussex Herminée',
      slug: 'poule-sussex-herminee',
      category: 'poules',
      description: 'La Sussex herminée est une magnifique poule au plumage blanc avec le camail noir.',
      shortDescription: 'Élégante poule anglaise au plumage blanc et noir.',
      price: 112500,
      images: ['https://images.unsplash.com/photo-1598965402089-897ce52e8355?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air'] as ProductBadge[],
      characteristics: ['200-250 œufs par an', 'Plumage blanc herminé', 'Très docile'],
      race: 'Sussex',
      eggColor: 'Crème',
    },
    {
      name: 'Poule Marans Noire Cuivrée',
      slug: 'poule-marans-noire-cuivree',
      category: 'poules',
      description: 'La Marans est LA poule française par excellence, célèbre pour ses œufs "extra-roux".',
      shortDescription: 'La reine des œufs extra-roux, plumage noir cuivré.',
      price: 135000,
      images: ['https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['150-200 œufs extra-roux par an', 'Race française du terroir', 'Rustique'],
      race: 'Marans',
      eggColor: 'Roux foncé',
    },
    {
      name: 'Poule Araucana',
      slug: 'poule-araucana',
      category: 'poules',
      description: 'L\'Araucana vous surprendra avec ses œufs naturellement bleu-vert !',
      shortDescription: 'La poule aux œufs bleus, originaire du Chili.',
      price: 157500,
      images: ['https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau', 'plein_air'] as ProductBadge[],
      characteristics: ['150-180 œufs bleus par an', 'Sans croupion', 'Très rustique'],
      race: 'Araucana',
      eggColor: 'Bleu-vert',
    },
    {
      name: 'Poule Soie Blanche',
      slug: 'poule-soie-blanche',
      category: 'poules',
      description: 'La poule Soie est irrésistible avec son plumage duveteux qui ressemble à de la soie !',
      shortDescription: 'Adorable poule d\'ornement au plumage soyeux.',
      price: 180000,
      images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['nouveau'] as ProductBadge[],
      characteristics: ['80-100 œufs par an', 'Plumage soyeux unique', 'Excellente couveuse'],
      race: 'Soie',
      eggColor: 'Crème',
    },
    // Accessoires (Désactivé)
    {
      name: 'Poulailler Bois 4-6 Poules',
      slug: 'poulailler-bois-4-6-poules',
      category: 'accessoires',
      description: 'Poulailler en bois traité autoclave, parfait pour 4 à 6 poules.',
      shortDescription: 'Poulailler robuste en bois pour 4 à 6 poules.',
      price: 850000,
      images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: [] as ProductBadge[],
      characteristics: ['Capacité : 4-6 poules', 'Bois traité autoclave', 'Toit bitumé imperméable'],
      dimensions: '150x80x100 cm',
    },
    {
      name: 'Aliment Poules Pondeuses Bio 20kg',
      slug: 'aliment-poules-pondeuses-bio-20kg',
      category: 'accessoires',
      description: 'Aliment complet bio pour poules pondeuses, formulé pour une ponte optimale.',
      shortDescription: 'Aliment complet bio pour une ponte optimale.',
      price: 112000,
      images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['bio', 'populaire'] as ProductBadge[],
      characteristics: ['Certifié Agriculture Biologique', 'Sans OGM', 'Riche en calcium'],
      weight: '20 kg',
    },
    {
      name: 'Abreuvoir Automatique 5L',
      slug: 'abreuvoir-automatique-5l',
      category: 'accessoires',
      description: 'Abreuvoir à réserve de 5 litres avec niveau constant.',
      shortDescription: 'Abreuvoir pratique à remplissage facile.',
      price: 58000,
      images: ['https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: [] as ProductBadge[],
      characteristics: ['Capacité 5 litres', 'Niveau d\'eau constant', 'Facile à nettoyer'],
    },
    {
      name: 'Mangeoire Anti-Gaspillage 10kg',
      slug: 'mangeoire-anti-gaspillage-10kg',
      category: 'accessoires',
      description: 'Mangeoire avec grille anti-gaspillage qui empêche les poules de gratter.',
      shortDescription: 'Mangeoire grande capacité anti-gaspillage.',
      price: 135000,
      images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      inStock: false,
      stockQuantity: 0,
      badges: ['populaire'] as ProductBadge[],
      characteristics: ['Capacité 10 kg', 'Grille anti-gaspillage', 'Couvercle étanche'],
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
  }
  console.log(`Created ${products.length} products`);

  // Seed Chicken Breeds
  const chickenBreeds = [
    {
      name: 'Marans Noire Cuivrée',
      slug: 'marans-noire-cuivree',
      image: 'https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=600'],
      eggColor: 'Roux foncé (chocolat)',
      eggColorHex: '#8B4513',
      temperament: 'Calme et docile',
      productivity: 'moyenne',
      productivityNumber: 65,
      eggsPerYear: '150-200',
      description: 'La Marans est une race française originaire de la ville de Marans en Charente-Maritime.',
      characteristics: ['Œufs d\'un beau roux foncé', 'Plumage noir aux reflets cuivrés', 'Excellente résistance au froid'],
      whyChoose: 'Choisissez la Marans pour la beauté incomparable de ses œufs chocolat !',
      origin: 'France (Charente-Maritime)',
      weight: 'Coq: 3,5-4 kg / Poule: 2,5-3 kg',
      available: true,
      price: 135000,
    },
    {
      name: 'Sussex Herminée',
      slug: 'sussex-herminee',
      image: 'https://images.unsplash.com/photo-1598965402089-897ce52e8355?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1598965402089-897ce52e8355?w=600'],
      eggColor: 'Crème à rosé',
      eggColorHex: '#FFF8DC',
      temperament: 'Très docile et sociable',
      productivity: 'élevée',
      productivityNumber: 85,
      eggsPerYear: '200-250',
      description: 'La Sussex est une race anglaise ancestrale. La variété herminée est la plus élégante.',
      characteristics: ['Plumage blanc avec camail noir', 'Excellente pondeuse', 'Très docile'],
      whyChoose: 'La Sussex herminée est le choix parfait pour les familles !',
      origin: 'Angleterre (Sussex)',
      weight: 'Coq: 4 kg / Poule: 3-3,5 kg',
      available: true,
      price: 112500,
    },
    {
      name: 'Poule Rousse Fermière',
      slug: 'poule-rousse-fermiere',
      image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      eggColor: 'Brun clair',
      eggColorHex: '#DEB887',
      temperament: 'Active et curieuse',
      productivity: 'très-élevée',
      productivityNumber: 95,
      eggsPerYear: '250-300',
      description: 'La poule rousse fermière est LA poule pondeuse par excellence !',
      characteristics: ['Championne de ponte', 'Très rustique', 'Facile à élever pour les débutants'],
      whyChoose: 'La rousse fermière est faite pour vous si vous cherchez une pondeuse efficace !',
      origin: 'Hybride (sélection française)',
      weight: 'Poule: 2,5-3 kg',
      available: true,
      price: 81000,
    },
    {
      name: 'Araucana',
      slug: 'araucana',
      image: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600'],
      eggColor: 'Bleu-vert',
      eggColorHex: '#87CEEB',
      temperament: 'Vive et indépendante',
      productivity: 'moyenne',
      productivityNumber: 60,
      eggsPerYear: '150-180',
      description: 'L\'Araucana est originaire du Chili. Elle pond des œufs naturellement bleu-vert !',
      characteristics: ['Œufs naturellement bleu-vert', 'Sans croupion', 'Très rustique'],
      whyChoose: 'L\'Araucana est un choix original pour les amateurs de diversité !',
      origin: 'Chili (Amérique du Sud)',
      weight: 'Coq: 2,5 kg / Poule: 2 kg',
      available: true,
      price: 157500,
    },
    {
      name: 'Poule Soie (Nègre-Soie)',
      slug: 'poule-soie',
      image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      eggColor: 'Crème rosé',
      eggColorHex: '#FFE4C4',
      temperament: 'Très docile et câline',
      productivity: 'faible',
      productivityNumber: 30,
      eggsPerYear: '80-100',
      description: 'La poule Soie est unique au monde avec son plumage duveteux qui ressemble à de la soie !',
      characteristics: ['Plumage soyeux unique', 'Peau et os noirs', '5 doigts', 'Excellente couveuse'],
      whyChoose: 'La poule Soie est parfaite si vous cherchez un animal de compagnie !',
      origin: 'Chine (Asie)',
      weight: 'Coq: 1,5 kg / Poule: 1-1,2 kg',
      available: true,
      price: 180000,
    },
  ];

  for (const breed of chickenBreeds) {
    await prisma.chickenBreed.create({ data: breed });
  }
  console.log(`Created ${chickenBreeds.length} chicken breeds`);

  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
